### ISSUE TITLE
没法运行，请问敏感区域是要把那个跳转到最底部的小气泡框起来吗

### ISSUE THREAD

**Issue by RestAutumn** [shuakami/qq-chat-exporter#1]
它每次都会点击到“跳转到底部的小气泡”上，根本没法运行，哪怕把气泡放在了铭感区域里也不行

**Comment by shuakami** [comment]
如果是这样的话，请提供完整复现视频（也就是从部署敏感区域到开始运行）。

**Comment by shuakami** [comment]
您可以先自己检查这些：
- 是否成功配置消息颜色？
- 是否已经把不可点击区域参数替换到qq.py？
- 尝试截图您自己的“跳转到底部的小气泡”图片，替换dist/fuck_down.png
![chrome_HuMXuUOlOo](https://github.com/user-attachments/assets/ab618167-a05b-48e7-8383-ba6ab6bcf0a2)

**Comment by shuakami** [comment]
如果超过7天未回复，此issues将关闭

**Comment by LingeringAutumn** [comment]
直接把小气泡截图成图片然后替换吗？

**Comment by shuakami** [comment]
没错。

**Comment by lurenjia-123** [comment]
test

**Comment by lurenjia-123** [comment]
test
